version: "3.7"
services:
  python-gui:
    build:
      dockerfile: ./docker/Dockerfile
    restart: always
    tty: true
    volumes:
      - ./:/home/user/code
    environment:
      - DISPLAY=${IPADDRESS}
